repo: 'berry-blobber'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    locked: true

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - 'var writeBerries \= function \('
      - 'forEach'
      - 'document.write\('
      - '\+'
      - '<h1>'
      - '<h2>'
      - '<dl>'
      - '<dt>'
      - '<dd>'

screenshots:
  - path: 'index.html'
    sizes: [320]
